#!/bin/bash

if test "$#" -lt 1
then
    echo "usage : $0 stretch or $0 jessie"
    exit 1;
fi

if ! type docker > /dev/null 2>&1
then
    echo "Docker not installed"
    exit 2
fi

docker run --rm -ti debian:"$@" /bin/bash -c "apt-get update && apt-get upgrade -y && apt-get install curl -y && curl https://raw.githubusercontent.com/Siweb-France/initialization/master/install.sh | bash ; /bin/bash"
